### ISSUE TITLE
Change folder-structure and filenames

### ISSUE THREAD

**Issue by fabcocco** [DanielGausi/Contao-CalendarEditor#2]
I would recommend to rename

/src/ContaoManager/Plugin.php --> /src/ContaoManager/ContaoManagerPlugin.php

and and a folder with the "vendor" name

/src/DanielGausi/calendar_editor/

**Comment by DanielGausi** [comment]
If I understand the system correctly, the Contao Manager will install it into /vendor/MyName/MyExtension with the current folder structure. I am still at the beginning of the migration from Contao 3 to 4, and have to figure out a lot of stuff. Probably there will be some notable progress during the next weekend here.
