### ISSUE TITLE
Contao 4.6

### ISSUE THREAD

**Issue by chriza** [DanielGausi/Contao-CalendarEditor#4]
Hallo,
das Modul EventEditor scheint nicht Contao 4.6 kompatibel zu sein.
Die Inhalte werden nicht abgesendet.

**Comment by DanielGausi** [comment]
Es scheint da ein Problem mit der Sicherheitsabfrage bei nicht angemeldeten usern zu geben. Bearbeitung für angemeldete Benutzer (Einstellung im Kalender) funktioniert bei mir. Ich hab im Forum mal nachgefragt, woran das liegen kann. In der Dokumentation bzw. Changelogs finde ich leider nichts dazu.

Zusatzfrage meinerseits: Der TinyMCE funktioniert bei Dir in 4.6 auch nicht, oder? ;-)

**Comment by DanielGausi** [comment]
Should be fixed in Release 4.2.

I don't close the issue right now, maybe I overlooked something. ;-)
